language: node_js
node_js:
- stable
sudo: false
notifications:
  slack:
    secure: Y7n27rR7h7hzDz8uN5eQEKh3Kogv8kMEv7Y+eZXfnRRN0RsMTUWmdXxnw8Lv00ubEFuhiCNhxAdDcs8gEs0fAadXpkSBgdZi6nHI+rfpjbvzsSpHRm3EcqNPPxlLakf8pXpq3PGAYYNKgztfPhjSNsQm/3VDdTt2khJuVY1DnTFmJE1Ss0ol8QgtusxDoC2JZ7LN8/0HoTWH1OZAQXwvouLLO14UPjhxTmG5dKfcvh1LJj0swG9+r5g8BVuoNvp6bi4G8xtvy8kcR2JZJwP62UaPqQhAlYeIdwG2LEu3qhkz2KiC9yjwizbEDNnJWU5ydUdmIlcXZG1tizavOR5T0Lz5oLBUziSPA+FcFh2IrLOsk0F3dvT9D5QEXfZ14rRM1NSEHIfG97CTEYdC65dCHgyhHGjzh8LKo/mWob9FFsGKO6aSdlrAIY00qtCqFPeJAe9VW3dh1VcTB3mBga/HgcWP7ySW87cPGGx7IFgRa+aDHhixECxUuf/SV4oHWumBWw06e+lGL9o2LJCF2yefsWRbFsg7xD+7nH9+ADFSn6BDL8DRspyJmZilsIw9HjRbCYq1NESKAQC/4Y6UfB9Ims3ML1Lu3u0HCMMC2OAJFS54c+pJUD56mr2K/Hu1kJg+xDKPm+ihPp9Jsld0zYd1tyonW/NYCLlXCnZMRWxttjw=
